#!/usr/bin/env bash
#Scripts to display Best School phrase 10 times but on 9th iteration print Hi on a new line also using while loop
i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	if [ $i -eq 8 ];then
		echo "Hi"
	fi
	i=$((i+1))
done 
