#!/usr/bin/env bash
#Scripts for displaying a 4 as bad luck, 8 as good luck, and other remaining numbers 8 times as Best School phrase using while loop and conditionals
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done 
