#!/usr/bin/env bash
#Scripts to prints bad luck from 3 countries such as China, Japan, and Italy
i=1 
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4) printf "bad luck from China\n"
		;;
		9) printf "bad luck from Japan\n"
		;;
		17) printf "bad luck from Italy\n"
		;;
	esac
	i=$((i+1))
done
