#!/usr/bin/env bash
#Scripts to prints bad luck from 3 countries such as China, Japan, and Italy
i=1 
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4) echo -e "bad luck from China "
		;;
		9) echo -e "bad luck from Japan"
		;;
		17) echo -e "bad luck from Italy"
		;;
	esac
	i=$((i+1))
done
